### ISSUE TITLE
Sprawdziłem zadania

### ISSUE THREAD

**Issue by k-basinski** [ag1zywert/komputerki#2]
Wszystko super. Następne zajęcia na których będzie coś ciekawego to zajęcia nr. 5:) Będziemy bawić się w `dplyr`. Na zajęciach 6 za to będzie o `R Markdown`.

**Comment by ag1zywert** [comment]
**Sztosik**, jak będzie Pan miał nowe zadanka szybciej czy coś to chętnie przyjmę szczególnie z ` R Markdown`, bo wlasnie sie ucze.
