### ISSUE TITLE
Sprawdziłem zadania 5

### ISSUE THREAD

**Issue by k-basinski** [ag1zywert/komputerki#3]
No prawie dobrze.... Tylko że:
- brakuje importu z pliku (powinna być linijka kodu z funkcją `read_csv()`)
- Pipe jest źle. Zwróć uwagę na to, co on właściwie robi - bierze wartość zwróconą przez jedną funkcję i przekazuje jako **pierwszy** argument drugiej funkcji. Czyli np tu:
```r
filter(movies, Animation == 1, year >=1990 & year < 2000) %>%
arrange(movies, desc(rating))
```
Nie ma sensu pisać `arrange(movies...`
- Jeśli dobrze użyć rury, nie ma w tych zadaniach w żadnym miejscu konieczności zdefiniowania jakiejkolwiek innej zmiennej niż `movies`

**Comment by ag1zywert** [comment]
Czyyyyli jak używam pipe'a to robię np.

`filter(movies, Animation == 1, year >=1990 & year < 2000) %>%
arrange (desc(rating))`

i to drugie porządkuje to co wypluwa to pierwsze?

* I jeśli robię pipe'a po raz drugi albo setny to ta funkcja odwołuje się do **poprzedniej** funkcji a nie całkiem **pierwszej**?

**Comment by k-basinski** [comment]
Tak, to się nazywa pipeline. Działa jak wodociąg. Od stacji do stacji, po rurach przekazywane są wartości. Generalnie poprawia to bardzo czytelność kodu i jest oszczędniejsze. Nie trzeba generować dodatkowych, zbędnych zmiennych. Nie trzeba też robić wielokrotnie zagnieżdżonych funkcji. Np.:
```r
# normalnie
mean(sqrt(abs(sin(x)))

# z pipeline
x %>% 
  sin() %>% 
  abs() %>% 
  sqrt() %>% 
  mean()
```

**Comment by ag1zywert** [comment]
Okej, dziękuję bardzo, wezmę to pod uwagę i poprawię co trzeba

**Comment by ag1zywert** [comment]
Ogólnie trochę mam problem z tą rurą, aż wstyd się przyznać, szczególnie przy zadaniu 5-8, umiem to zrobić robiąc nową zmienną z tych filmów < 200', tak jak dodalam, ale z rurą mam problem 

` ggplot(data = movies) +
    geom_freqpoly(mapping = aes(length), bindwith = 1) %>%
      filter(length < 200)` 

no bo tak nie działa i nwm w którym miejscu wsadzić pipea i w jakiej kolejności to zrobic

**Comment by k-basinski** [comment]
Pipe zawsze działą od lewej do prawej. Bierze to co jest wynikiem wyrażenia z lewej i wrzuca jako pierwszy argument tego co po prawej. Czyli kolejnośc dokładnie na odwrót:)

**Comment by ag1zywert** [comment]
zrobiłam z rurką to 5-8 pkt 1, ale ten pkt 2 to  help, bo nie wiem jak to z tym ifelsem ugryzc ¯\_(ツ)_/¯

**Comment by k-basinski** [comment]
Ok. Podpowiedź - przyda się nowa zmienna, która zakoduje czy coś jest krótkim czy nie jest krótkim metrażem. Coś w stylu:

`mutate(is_short = ifelse(Short == 1, TRUE, FALSE))`

**Comment by ag1zywert** [comment]
A po ifelsie można już zrobić nierówność w sensie `mutate(is_short = ifelse(length > 50, TRUE, FALSE))` czy nie?
